repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: requirements-txt-fixer
      name: Requirements
      types: [file]
      exclude_types: ['image']
    - id: debug-statements
      name: Debugging
      language: python
      types: [file, python]
      exclude_types: ['image']
    - id: trailing-whitespace
      name: Trailing Whitespace
      language: python
      types: [file]
      exclude_types: ['image']
    - id: check-yaml
      name: YAML Structure
      language: python
    - id: check-toml
      name: TOML Structure
    - id: check-merge-conflict
      name: Merge Conflicts
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
    - id: black
      name: Black Formatting
      language: python
      types: [file, python]
      args: [--line-length=100]

ci:
  autofix_prs: true
  autofix_commit_msg: "ci: correct from checks."
